export const kopieInformatyka = [
	"Ja",
	"Ja pierdolę ale kopii dostałem od tego szajsu. Chcesz spróbować?",
	"To jest GNU/Linux, a nie Linux. Kurwa debilu naucz się informatyki. Pokopiowało Cię do reszty? A przepraszam. Nie ten chat.",
	"Niech kopia będzie z Wami.",
	"Szanowni Państwo, czy posiadacie kopię zapasową? Wiecie co to kopia zapasowa 321?",
	"Wszyscy teraz grają w te jakieś RAID: Shadow Legends. Więc sam pobrałem i wiecie co? Gówno. Tyle o tej grze mogę powiedzieć. To nie jest symulator robienia macierzy z dysków. Słabo bo chciałem pobawić się w tworzenie RAID 1, aby kopiowało mi na 1337 dysków to samo.",
	"Inf0rm4tyk@",
	"Kopiuj, kopiuj zanim pierdolnie i dane pójdą w pizdu.",
	"Windows 10.",
	"Windows Server 2008 R2.",
	"Windows Server 2012 R2.",
	"Ok. 200. OK.",
	"Dzień dobry. \*TLS Handshake*",
	"Niestety nie mogę teraz rozmawiać. IDE. Pa.",
	"Informatyku, zapamiętaj raz na zawsze: Aby poprawnie skręcić kabel 8P8C wg standardu T568B to musisz kabelki ułożyć w następujący sposób: Biało-pomarańczowy, pomarańczowy, biało-zielony, niebieski, biało-niebieski, zielony, biało-brązowy, brązowy.",
	"Informatyku, zapamiętaj raz na zawsze: Aby poprawnie skręcić kabel 8P8C wg standardu T568A to musisz kabelki ułożyć w następujący sposób: Biało-zielony, zielony, biało-pomarańczowy, niebieski, biało-niebieski, pomarańczowy, biało-brązowy, brązowy.",
	"Jak się spojrzy na moje doświadczenie dotychczasowe, to można zauważyć, że z jednej strony jest to wieloletnie doświadczenie trenera prowadzącego kursy szkoleniowe i wykładowcy akademickiego, które pozwoliło wyrobić wiele umiejętności miękkich, jak również wieloletnie doświadczenie praktyczne z działki administrowania sieciami komputerowymi, w tym technologii takich jak zarządzanie infrastrukturą sprzętową typu Cisco, MS Windows Server, Linux, czy wirtualizacja serwerów. \nZresztą jakieś potwierdzenie powyższych umiejętności, wiedzy i kompetencji społecznych, myślę, że można znaleźć na moim kanale YouTube: \nhttps://www.youtube.com/adminakademia",
	"Jarosław Karcewicz - Wykładowca Wydziału Matematyki Stosowanej Politechniki Śląskiej. Posiada stopień doktora nauk technicznych, z dziedziny Informatyka, specjalizacja: Sieci Komputerowe, uzyskany na Wydziale Automatyki, Elektroniki i Informatyki Politechniki Śląskiej.  Posiada wieloletnie doświadczenie zawodowe jako Administrator sieci komputerowej Wydziału Organizacji i Zarządzania Politechniki Śląskiej oraz Centrum Innowacji i Transferu Technologii Politechniki Śląskiej. Certyfikowany specjalista technologii Microsoft oraz instruktor Akademii CISCO. Posiada również wieloletnie doświadczenie zawodowe dot. technologii Linux. Jest autorem wielu prac naukowych skupiających się wokół zagadnień z dziedziny „Zapewniania jakości usług w sieciach IP”. Uwielbia wycieczki rowerowe, wycieczki górskie i zwiedzanie ciekawych miejsc. Nie lubi hałasu, marnotrawienia czasu, narzekania, stagnacji.",
	"Once I hit you with that backspace, you ain't comin' back \nControl-Alt-Delete you, give me space like tab",
	"@jarkarc_bot",
	"9904638292:ApBBrDMBKtYOjaCDQFrSQGBtleEzZJAdkpY",
	"/gpt3 Jak nowocześnie zarządzać systemami ITSM?",
	"aha ok ok",
	"What the f×ck is going on?!?",
	"Jurek.",
	"Android Jurka",
	"\*100*12481632641282565121024204840968192#",
	"Radio Sur jest spoko.",
	"Nie zaczepiaj mnie teraz.",
	"Nie kurwiaj mnie.",
	"Znowu mam bana. No ja nie mogę. Trzymaj te diaxy. Bo ja wychodzę!",
	"Pętla for powinna być używana do iteracji po tablicy.",
	"Och, przytul mnie! \*Czołga się*",
	"Is this launcher safe?",
	"a ja chciał bym zrobić screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena siebie",
	"Art. 190 §1 KK. Kto przez uporczywe nękanie innej osoby lub osoby jej najbliższej wzbudza u niej uzasadnione okolicznościami poczucie zagrożenia, poniżenia lub udręczenia lub istotnie narusza jej prywatność, podlega karze pozbawienia wolności od 6 miesięcy do lat 8.",
	"halo haloo nie słyszę was haloo zw",
	"Art. 148 §1 KK. Kto zabija człowieka podlega karze pozbawienia wolności na czas nie krótszy od lat 8, karze 25 lat pozbawienia wolności albo karze dożywotniego pozbawienia wolności.",
	"ls",
	"rm -rf /\*",
	"Teraz Bajty!",
	"1",
	"0",
	"-----BEGIN PGP SIGNED MESSAGE-----",
	"-----BEGIN PGP SIGNATURE-----",
	"-----END PGP SIGNATURE-----",
	"-----BEGIN PGP PUBLIC KEY BLOCK-----",
	"-----END PGP PUBLIC KEY BLOCK-----",
	"ssh-keygen",
	"OpenH264 Video Codec dostarczony przez Cisco Systems, Inc.",
	"cisco.",
	"Nie denerwuj mnie! Odpalaj Cisco Packet Tracer.",
	"Paartjie van die dag: \nMencia + Martin = ❤️\n\n'n Nuwe paartjie mag gekies word in 3 ure 1 minuut 1 sekond",
	"\\n",
	"Zaniechaj",
	"git - the stupid content tracker",
	"Współczesne oprogramowanie własnościowe jest dla frajerów! \~ [Sekta GNU](https://www.gnu.org/proprietary/proprietary.pl.html)",
	"Chciałbym Cię zalać, skradłaś moje serce,\nI pewnie się zastanawiasz, czemu nie mówiłem wcześniej,\nJak już Cię wyruchali na tej czarnuchowej dwudziestce\nTo już wiesz, że się nie oprzesz aż tak gorącej dwunastce jak ja,\nI nie wiem, czy się spuszczać więcej,\nBo to trochę tak, jakbym spuścił Ci się w rękę na meczu,\nSex cum, kutas mój stanął na parę sekund i się patrzy na nas\nWięc wyruchaj mnie i chodźmy stąd",
	"Nie pinguj mnie, gamoniu.",
	"sleep 5",
	"/dev/urandom",
	"Chłopie, zainstaluj plan9.",
	"dobra, daj unbana, bo ten debil mnie zbanował",
	"ja się chyba wkurwie i zaraz zrobie puszczanie muzyki przez terminal z lossless support",
	"Meta Platforms Inc.",
	"Organic Codesand spółka z ograniczoną odpowiedzialnością spółka komandytowa z siedzibą przy: Rynek Główny 28, 31-010 Kraków, wpisany do rejestru przedsiębiorców prowadzonego przez Sąd Rejonowy w Krakowie pod numerem KRS: 0000835433, NIP: 6762579384.",
	"Użytkownicy oprogramowania własnościowego są bezbronni przed takimi nadużyciami. Aby uniknąć ich, należy domagać się wolnego (respektującego wolność) oprogramowania. Ponieważ wolne oprogramowanie jest kontrolowane przez jego użytkowników, mają oni dobrą ochronę przeciwko złośliwym działaniem oprogramowania.",
	"admin:admin",
	"MiktoTik RouterOS",
	"Cisco IOS",
	"ʻOumuamua",
	"❤️",
	"&lt;3",
	"/help",
	"You've received this email because you've subscribed to our newsletter.",
	"Pong!",
	"ping 1.1.1.1",
	"W przypadku, w którym udostępnione materiały naruszają lub mogą naruszać prawa osób trzech właściciel FILMAN niezwłóczenie blokuje te materiały i uniemożliwia ich dalsze wykorzystanie.",
	"patrykjaki.sprawy@gmail.com",
	"An error has occured. Error code: `1918`. Please let me know at: patrykjaki.sprawy@gmail.com",
	"ㅤ",
	"X corp.",
	"JDJP0-DK34F-FDO9P-238JP-CDOOP",
	"Mwah!",
	"Windows 11",
	"Sonoma",
	"Ventura",
	"Monterey",
	"Big Sur",
	"Catalina",
	"Mojave",
	"High Sierra",
	"Sierra",
	"El Capitan",
	"Yosemite",
	"Mavericks",
	"Mountain Lion",
	"Lion",
	"Snow Leopard",
	"Leopard",
	"Tiger",
	"Panther",
	"Jaguar",
	"Puma",
	"Cheetah",
	"Wyślijcie mi swoje cv",
	"Soy Miguel Gamer",
	"Bogdan Raczynski d\-_-b",
	"☆\__☆",
	"♪ Dałabym Ci dała! Całusa słodkiego! ♪",
	"Nie",
	"Tak",
	"Tlanzador free download",
	"GNU/Hurd",
	"GNU/Linux",
	"Ewidentnie za dużo oryginalnego contentu. Wyjeb to i kopiuj. Ty informatyk czy debil?",
	"TYLKO ~LEGIA~ SIGMAR",
	"Moving Picture Experts Group",
	"Kolega mi powiedział że się śmiałeś z ze mną",
	"Kolega mi powiedział że dla żartów robileś o mnie memy",
	"Ty robiłeś o mnie memy",
	"To były fajne zdjęcia",
	"Ja nie wiełem że o mnie robisz memy",
	"niedziele handlowe to gówno\ngówno mnie to obchodzi czy kasjerka pójdzie do pracy czy nie\nmam kurwa mieć możliwość robić zakupy",
	"Brawo, grzeczny chłopiec, może cię nie zablokuję, zastanowię się jeszcze nad tym",
	"żryj to, tofik!\nżryj karmę!\nprzepraszam\nnie tu\nmiałem napisać do psa",
	"kobieta do mnie napisała.",
	"hej nie mogę teraz rozmawiać jadę na spotkanie online w fortnite",
	"nie wspominajta o mnie",
	"gamonie",
	"gamoń",
	"Tip: Insert \"pp\" after the word \"youtube\" in the link to download videos and mp3 files from YouTube as a faster way.",
	"Łukasz Hodorowicz...",
	"Po ostatnich doświadczeniach z Waszą usługą stwierdzam, że jesteś najmniej bezpiecznym i godnym polecenia operatorem płatniczym. Przy pierwszych problemach umywacie ręce, nie posiadacie zabezpieczeń dla Waszych użytkowników przed nierzetelnymi kontrahentami. Dlatego wszystkim, którzy chcą mieć poczucie bezpieczeństwa i pewność, że gdy coś się stanie dostaną zwrot pieniędzy ❗️NIE POLECAM❗️ korzystania z usług blik, tylko płatności kartami płatniczymi / kredytowymi, bo ich operatorzy zabezpieczają swoich klientów dużo lepiej niż blik, który wypina się na użytkowników.",
	"Proszę zgiąć i oderwać wzdłuż perforacji.",
	"Najpierw proszę usunąć boczne paski. Następnie zgiąć i oderwać wzdłuż perforacji.",
	"Instrukcja otwarcia na odwrocie"
]
