export default [
	"Ja",
	"Ja pierdolę ale kopii dostałem od tego szajsu. Chcesz spróbować?",
	"To jest GNU/Linux, a nie Linux. Kurwa debilu naucz się informatyki. Pokopiowało Cię do reszty? A przepraszam. Nie ten chat.",
	"Niech kopia będzie z Wami.",
	"Szanowni Państwo, czy posiadacie kopię zapasową? Wiecie co to kopia zapasowa 321?",
	"Wszyscy teraz grają w te jakieś RAID: Shadow Legends. Więc sam pobrałem i wiecie co? Gówno. Tyle o tej grze mogę powiedzieć. To nie jest symulator robienia macierzy z dysków. Słabo bo chciałem pobawić się w tworzenie RAID 1, aby kopiowało mi na 1337 dysków to samo.",
	"Inf0rm4tyk@",
	"Kopiuj, kopiuj zanim pierdolnie i dane pójdą w pizdu.",
	"Windows 10.",
	"Windows Server 2008 R2.",
	"Windows Server 2012 R2.",
	"Ok. 200. OK.",
	"Dzień dobry. \*TLS Handshake*",
	"Niestety nie mogę teraz rozmawiać. IDE. Pa.",
	"Informatyku, zapamiętaj raz na zawsze: Aby poprawnie skręcić kabel 8P8C wg standardu T568B to musisz kabelki ułożyć w następujący sposób: Biało-pomarańczowy, pomarańczowy, biało-zielony, niebieski, biało-niebieski, zielony, biało-brązowy, brązowy.",
	"Informatyku, zapamiętaj raz na zawsze: Aby poprawnie skręcić kabel 8P8C wg standardu T568A to musisz kabelki ułożyć w następujący sposób: Biało-zielony, zielony, biało-pomarańczowy, niebieski, biało-niebieski, pomarańczowy, biało-brązowy, brązowy.",
	"Jak się spojrzy na moje doświadczenie dotychczasowe, to można zauważyć, że z jednej strony jest to wieloletnie doświadczenie trenera prowadzącego kursy szkoleniowe i wykładowcy akademickiego, które pozwoliło wyrobić wiele umiejętności miękkich, jak również wieloletnie doświadczenie praktyczne z działki administrowania sieciami komputerowymi, w tym technologii takich jak zarządzanie infrastrukturą sprzętową typu Cisco, MS Windows Server, Linux, czy wirtualizacja serwerów. \nZresztą jakieś potwierdzenie powyższych umiejętności, wiedzy i kompetencji społecznych, myślę, że można znaleźć na moim kanale YouTube: \nhttps://www.youtube.com/adminakademia",
	"Jarosław Karcewicz - Wykładowca Wydziału Matematyki Stosowanej Politechniki Śląskiej. Posiada stopień doktora nauk technicznych, z dziedziny Informatyka, specjalizacja: Sieci Komputerowe, uzyskany na Wydziale Automatyki, Elektroniki i Informatyki Politechniki Śląskiej.  Posiada wieloletnie doświadczenie zawodowe jako Administrator sieci komputerowej Wydziału Organizacji i Zarządzania Politechniki Śląskiej oraz Centrum Innowacji i Transferu Technologii Politechniki Śląskiej. Certyfikowany specjalista technologii Microsoft oraz instruktor Akademii CISCO. Posiada również wieloletnie doświadczenie zawodowe dot. technologii Linux. Jest autorem wielu prac naukowych skupiających się wokół zagadnień z dziedziny „Zapewniania jakości usług w sieciach IP”. Uwielbia wycieczki rowerowe, wycieczki górskie i zwiedzanie ciekawych miejsc. Nie lubi hałasu, marnotrawienia czasu, narzekania, stagnacji.",
	"Once I hit you with that backspace, you ain't comin' back \nControl-Alt-Delete you, give me space like tab",
	"@jarkarc_bot",
	"9904638292:ApBBrDMBKtYOjaCDQFrSQGBtleEzZJAdkpY",
	"/gpt3 Jak nowocześnie zarządzać systemami ITSM?",
	"aha ok ok",
	"What the f×ck is going on?!?",
	"Jurek.",
	"Android Jurka",
	"\*100*12481632641282565121024204840968192#",
	"Radio Sur jest spoko.",
	"Nie zaczepiaj mnie teraz.",
	"Nie kurwiaj mnie.",
	"Znowu mam bana. No ja nie mogę. Trzymaj te diaxy. Bo ja wychodzę!",
	"Pętla for powinna być używana do iteracji po tablicy.",
	"Och, przytul mnie! \*Czołga się*",
	"Is this launcher safe?",
	"a ja chciał bym zrobić screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena screena siebie",
	"Art. 190 §1 KK. Kto przez uporczywe nękanie innej osoby lub osoby jej najbliższej wzbudza u niej uzasadnione okolicznościami poczucie zagrożenia, poniżenia lub udręczenia lub istotnie narusza jej prywatność, podlega karze pozbawienia wolności od 6 miesięcy do lat 8.",
	"halo haloo nie słyszę was haloo zw",
	"Art. 148 §1 KK. Kto zabija człowieka podlega karze pozbawienia wolności na czas nie krótszy od lat 8, karze 25 lat pozbawienia wolności albo karze dożywotniego pozbawienia wolności.",
	"ls",
	"rm -rf /\*",
	"Teraz Bajty!",
	"1",
	"0",
	"-----BEGIN PGP SIGNED MESSAGE-----",
	"-----BEGIN PGP SIGNATURE-----",
	"-----END PGP SIGNATURE-----",
	"-----BEGIN PGP PUBLIC KEY BLOCK-----",
	"-----END PGP PUBLIC KEY BLOCK-----",
	"ssh-keygen",
	"OpenH264 Video Codec dostarczony przez Cisco Systems, Inc.",
	"cisco.",
	"Nie denerwuj mnie! Odpalaj Cisco Packet Tracer.",
	"Paartjie van die dag: \nMencia + Martin = ❤️\n\n'n Nuwe paartjie mag gekies word in 3 ure 1 minuut 1 sekond",
	"\\n",
	"Zaniechaj",
	"git - the stupid content tracker",
	"Współczesne oprogramowanie własnościowe jest dla frajerów! \~ [Sekta GNU](https://www.gnu.org/proprietary/proprietary.pl.html)",
	"Chciałbym Cię zalać, skradłaś moje serce,\nI pewnie się zastanawiasz, czemu nie mówiłem wcześniej,\nJak już Cię wyruchali na tej czarnuchowej dwudziestce\nTo już wiesz, że się nie oprzesz aż tak gorącej dwunastce jak ja,\nI nie wiem, czy się spuszczać więcej,\nBo to trochę tak, jakbym spuścił Ci się w rękę na meczu,\nSex cum, kutas mój stanął na parę sekund i się patrzy na nas\nWięc wyruchaj mnie i chodźmy stąd",
	"Nie pinguj mnie, gamoniu.",
	"sleep 5",
	"/dev/urandom",
	"Chłopie, zainstaluj plan9.",
	"dobra, daj unbana, bo ten debil mnie zbanował",
	"ja się chyba wkurwie i zaraz zrobie puszczanie muzyki przez terminal z lossless support",
	"Meta Platforms Inc.",
	"Organic Codesand spółka z ograniczoną odpowiedzialnością spółka komandytowa z siedzibą przy: Rynek Główny 28, 31-010 Kraków, wpisany do rejestru przedsiębiorców prowadzonego przez Sąd Rejonowy w Krakowie pod numerem KRS: 0000835433, NIP: 6762579384.",
	"Użytkownicy oprogramowania własnościowego są bezbronni przed takimi nadużyciami. Aby uniknąć ich, należy domagać się wolnego (respektującego wolność) oprogramowania. Ponieważ wolne oprogramowanie jest kontrolowane przez jego użytkowników, mają oni dobrą ochronę przeciwko złośliwym działaniem oprogramowania.",
	"admin:admin",
	"MiktoTik RouterOS",
	"Cisco IOS",
	"ʻOumuamua",
	"❤️",
	"&lt;3",
	"/help",
	"You've received this email because you've subscribed to our newsletter.",
	"Pong!",
	"ping 1.1.1.1",
	"W przypadku, w którym udostępnione materiały naruszają lub mogą naruszać prawa osób trzech właściciel FILMAN niezwłóczenie blokuje te materiały i uniemożliwia ich dalsze wykorzystanie.",
	"patrykjaki.sprawy@gmail.com",
	"An error has occured. Error code: `1918`. Please let me know at: patrykjaki.sprawy@gmail.com",
	"ㅤ",
	"X corp.",
	"JDJP0-DK34F-FDO9P-238JP-CDOOP",
	"Mwah!",
	"Windows 11",
	"Sonoma",
	"Ventura",
	"Monterey",
	"Big Sur",
	"Catalina",
	"Mojave",
	"High Sierra",
	"Sierra",
	"El Capitan",
	"Yosemite",
	"Mavericks",
	"Mountain Lion",
	"Lion",
	"Snow Leopard",
	"Leopard",
	"Tiger",
	"Panther",
	"Jaguar",
	"Puma",
	"Cheetah",
	"Wyślijcie mi swoje cv",
	"Soy Miguel Gamer",
	"Bogdan Raczynski d\-_-b",
	"☆\__☆",
	"♪ Dałabym Ci dała! Całusa słodkiego! ♪",
	"Nie",
	"Tak",
	"Tlanzador free download",
	"GNU/Hurd",
	"GNU/Linux",
	"Ewidentnie za dużo oryginalnego contentu. Wyjeb to i kopiuj. Ty informatyk czy debil?",
	"TYLKO ~LEGIA~ SIGMAR",
	"Moving Picture Experts Group",
	"Kolega mi powiedział że się śmiałeś z ze mną",
	"Kolega mi powiedział że dla żartów robileś o mnie memy",
	"Ty robiłeś o mnie memy",
	"To były fajne zdjęcia",
	"Ja nie wiełem że o mnie robisz memy",
	"niedziele handlowe to gówno\ngówno mnie to obchodzi czy kasjerka pójdzie do pracy czy nie\nmam kurwa mieć możliwość robić zakupy",
	"Brawo, grzeczny chłopiec, może cię nie zablokuję, zastanowię się jeszcze nad tym",
	"żryj to, tofik!\nżryj karmę!\nprzepraszam\nnie tu\nmiałem napisać do psa",
	"kobieta do mnie napisała.",
	"hej nie mogę teraz rozmawiać jadę na spotkanie online w fortnite",
	"nie wspominajta o mnie",
	"gamonie",
	"gamoń",
	"Tip: Insert \"pp\" after the word \"youtube\" in the link to download videos and mp3 files from YouTube as a faster way.",
	"Łukasz Hodorowicz...",
	"Proszę zgiąć i oderwać wzdłuż perforacji.",
	"Najpierw proszę usunąć boczne paski. Następnie zgiąć i oderwać wzdłuż perforacji.",
	"Instrukcja otwarcia na odwrocie",
	"Po ostatnich doświadczeniach z Waszą usługą stwierdzam, że jesteś najmniej bezpiecznym i godnym polecenia operatorem płatniczym. Przy pierwszych problemach umywacie ręce, nie posiadacie zabezpieczeń dla Waszych użytkowników przed nierzetelnymi kontrahentami. Dlatego wszystkim, którzy chcą mieć poczucie bezpieczeństwa i pewność, że gdy coś się stanie dostaną zwrot pieniędzy ❗️NIE POLECAM❗️ korzystania z usług blik, tylko płatności kartami płatniczymi / kredytowymi, bo ich operatorzy zabezpieczają swoich klientów dużo lepiej niż blik, który wypina się na użytkowników.",
	"Tylko raz zdarzyło mi się jechać gdzieś bez prawa jazdy. Żałuję tego niesamowicie i już nigdy nie popełniłbym tego czynu. Na swoje usprawiedliwienie mam tylko to, że prawo jazdy miałem, ale niestety nie przy sobie.",
	"Bogdan.",
	"Uwaga: Nie zmieniaj tytułu ani kwoty przelewu! \nPrzelew z innym tytułem lub kwotą może nie dotrzeć do sprzedającego! \nJeżeli płacisz z rachunku zagranicznego i przewalutowanie zmieni kwotę, płatność może zostać anulowana.",
	"Allegro Protect",
	"Allegro PROTECC",
	"Przepraszam bardzo serdecznie, ale aktualnie moje włosy są obcinane przez zewnętrznego kontraktora. Proszę nie przeszkadzać.",
	"O kurwa! Jestem BIZNESEM!",
	"Rozprawę poprowadzi sędzia Artur Lipiński.",
	"Rozprawę poprowadzi sędzia Anna Maria Wesołowska.",
	"Free Fortnite XP download",
	"Use Control + Shift + M to toggle the tab key moving focus. Alternatively, use esc then tab to move to the next interactive element on the page.",
	"Sposoby na oszczędzanie mają",
	"Pobieranie tlanzador.jar (lewo 50MB)",
	"Lewe foldery",
	"Nie prezentuj mi tego gówna!",
	"Co ty mi tu przedstawiasz, hakerze?",
	"CO TY TU HAKUJESZ! Nie kombinuj!",
	"Taki z Ciebie fan wolnego oprogramowania? To dawaj, wyślij mi przelew przelewem tradycyjnym na kartce. Zobaczymy jak będzie Ci wygodnie wykonać przelew!",
	"Hey! I'm a simple bot that will send you chat actions. Use /start to get a list of actions to send.",
	"Kurwa! Ten komputer jest taki czarny, że zaraz zacznie rapować! Po chuj było stawiać na tym koparki monero?",
	"Zdrada i krzywda i miłość i rozwód i separacja i zazdrość i kurator i alimenty.",
	"srać mi się chce",
	"zjebalo sie",
	"MATeMAtyka",
	"Przygotuj swoje basy, bo za 30 sekund rozpoczyna się grupowe basowanie! Dołącz do innych w wirtualnym jam session i poczuj rytm wspólnie.",
	"Zuck is a CUCK!",
	"Nothing",
	"https://osu.ppy.sh/",
	"Witam. Ja jestem Jakub Malec, a to jest program Tech - To Logiczne. Dzisiaj patrzymy na komputer.",
	"Ja mam AI w komputerze. Jak se wejdę w bios, nie? TO ja tam mam normalnie AI tweaker wyobraź sobie ziomuś :O",
	"69",
	"Czy ten procesor jest napastowany?",
	"Moje dziecko nie będzie mogło oglądać YouTube'a, bo tak ludzie będą go śledzić! Na Facebooku wyczytałem :>",
	"odpal fortnite",
	"No całkiem sporo tej śmiechawy było, NIEZŁY ubaw.",
	"zainstaluj rozszerzenie do chrome \"video downloader plus\" klikasz zapisz i juz",
	"Chlew to ty robisz na tym forum. Jestem kobietą bardzo dobrze wykształconą, mam dzieci które wychowałam na przyzwoitych ludzi i jestem zwolenniczką pis - proszę nie używać takich stwierdzeń. O wiele większe zło uczynione przez kałowców było wcześniej i będzie teraz...",
	"Co za przygłup wrzucił wersje dla niewidzących?!",
	"widać musiałeś się naoglądać za dzieciaka jak ci w matke wbijali xd",
	"Dean Herbert\n41 Gregory Street\nWembley, WA, 6014\nAustralia",
	"Bezczelna, zakłamana, antypolska, rasistowska żydówa !!!\nTFUUU jej w pysk !!!!!",
	"Właściciel FILMAN dokłada najwyższych starań, by wszelkie treści dostarczane przez ten portal nie naruszały praw osób trzecich. W szczególności zaś, zgodnie z najlepszą wiedzą właściciela FILMAN, materiały udostępniane na stronie są materiałami, których wykorzystanie w ramach FILMAN nie narusza prawa autorskich osób trzecich (linking), a usuniecie materiałów ze strony źródłowej usunie materiał także w FILMAN. FILMAN nie przechowuje (hostuje) tych materiałów. Dodatkowo, właściciel FILMAN na bieżąco monitoruje udostępniane treści.",
	"i teraz wysoki sądzie zachodzę w głowę czemu tak dużo używam linux nie umie tak dużo.",
	"Tańcz, tańcz, tańcz, dopóki nie odpadniesz\nTańcz, tańcz, tańcz, jak hooligan\nRęce w górę, niech twój głos stanie się głośny\nPrzyjdź razem, robimy to non stop",
	"Tiesto nie je káblik. Je to sušienka.",
	"Tiesto, słynny DJ, nie mógł uwierzyć, gdy jego najnowszy komputer odmówił współpracy. Ekran był niebieski, a klawiatura wydawała dziwne dźwięki.",
	"\"Myślałem, że to klawiatura\" - powiedział Tiesto. \"Ale okazało się, że to Bluetooth się odłączył\".",
	"Powinienem był wiedzieć, że Bluetooth to zły tancerz",
	"Tiesto naprawił komputer dzięki żartowi informatycznemu o Bluetooth.",
	"Dlaczego komputer miał katar? Bo miał wirusa!",
	"Tiesto, zakochany w muzyce, kupił komputer, który \"gra\" tylko dzwonki. Okazało się, że to... Ale przynajmniej teraz ma doskonałe tło dźwiękowe do pracy! W końcu odkrył, że muzyka to więcej niż tylko dźwięki z komputera. Tiesto kupił komputer, który grał tylko dzwonki; odkrył piękno muzyki.",
	"Tiesto, zapalony DJ, kupił komputer zamiast miksera. Przyciskając \"play\", zrobił reset całego miasta. \"Mixuj mądrze, by uniknąć awarii!\" Tiesto zakupił komputer, co spowodowało katastrofę, lecz uczył się, jak unikać awarii.",
	"JAKI ZNOWU SPRYCIARZ TYTAJ USUNĄŁ JARKARC",
	"spryciarze.pl",
	"kurwa czy mój bot nie działa od miesięcy",
	"sprytny jestes ziomus",
	"sam & cat online watch, sam & cat watch free online, sam & cat streaming online, sam & cat episode stream, sam & cat online tv download, watch sam & cat online",
	"@Sexiarz",
	"Hey, I’m Neil Patel.\n\nI’m determined to make a business in Warsaw successful.\n\nMy only question is, will it be yours?",
	"Kocham Shinyę i zobowiązuję się do oddania duszy dla wyżej wspomnianego przeze mnie perkusisty.",
	"esakalanzador",
	"od kiedy ty w apple pracujesz?",
	"ID: 1",
	"5410375023:M_NbhtRCjftjomzmDEEGKgi_sxKLuUXKYey",
	"https://t.me/ribonedrinksreview",
	"DJ TĘPA KNAGA",
	"Chodź do Jaworzna to mnie znajdziesz.",
	"Kop sprzęgło przy komendzie policji.",
	"MIKSUJE DLA WAS DJ PIERDOLONA WIERTARKO-WKRĘTARKA",
	"DJ TĘGA KNAGA",
	"mix tak mocny ze stary wyjebał mi z pokoju panele i zamienił je na azbest",
	"Chłop jest jak serce, jak bije to dobrze",
	"Baba to jest jak drzwi, jak nie pierdolniesz to się nie zamknie.",
	"Dziekuje za nutke przez przypadek skopalem sasiadke i skakalem 13 latce po glowie i dostalem zakaz zblizania sie do przedszkola oraz dostalem zaproszenie od ecpu na fb ale spokojnie naszczescie odrzucilem je wiec wiem ze jestem safe pozdrawiam oczywiscie wszystko w gtaV",
	"Dzień dobry. Czy to Twój komunikator internetowy?",
	"Czy bicie żony kablem HDMI 2.1 ultra high poprawia jakość jej bicia?",
	"Po tym filmie widać, że Boxdel to nie tylko postać z internetu, ale naprawdę głęboka osobowość.",
	"Ale ta Jinx mi się podoba Ale bym ruchał. Tak jak Jan Paweł II ruchał dzieci",
	"Weź ty sie umów do psychologa człowieku haha",
	"Bym z tej Jinx nie schodził cały dzień. Ruchałbym ją 30 razy na dzień",
	"relujesz bratku japi3rdole taka rakieta",
	"Nareszcie ktoś szczery w komentarzach. Zazwyczaj mi się takie punkowe dziewczyny nie podobają ale Jinx bym po prostu rżnął i ruuchał bez przerwy. Z rana bym musiała obciągać a w nocy by nie spała.",
	"przeciez to kazdej z nich marzenie, skad sie wziol syndrom szwedzki, wlasnie po takiej co porwali ja we 2ch, dojezdzali codziennie, codziennie rano musiala ciagnac pod stolem jak chciala smietanke do kawy, gdy oni jedli sniadanie. i gdy w koncu ja u nich znalezli , na procesie zeby ich wypuscili bo ona ich obu kocha. i wlasnie tak jest jak maz szlaufe bije to jej watroba od wodki co razem pija nie gnije, i ona nie moze odejsc, to skomplikowane, i tam nie ma gwaltu rozwodowego bo on za nudny byl dla niej. samo zycie. kazda tepa szm.ta otwiera ryj zebys jej go zatkal. im bardziej pyskata tym bardziej lubi. ba powiem ci lepiej, ona nawet nie zna slowa mizoginia. gdzie reszta zna ale nie wie co znaczy. dlatego sie same osmieszaja najlepiej",
	"Ja jestem blackpilowcem. I ogólnie nienawidzę feminizmu zwłaszcza pop kulturze. woke i murzyni też mnie mierzną",
	"ja do murzynow nic nie mam, dzis dzieki internetowi mozna poznac inne kultury, nacje, kolor skory, jak komus nie pasuje nie musi tam jechac, ale my nie mozemy tego popierac u nas, a najwiecej krzycza czarnuchy, gdzie prawda jest taka ze sa zbyt leniwi i tepi i szukaja tylko niewolnikow co beda na nich robic jak szlaufy. ale one byly tak tepe ze chcialy rownouprawnienia i teraz nagle go nie chca, bo kopie je w dupe. a ja bardzo lubie jak ludzie dostaja to na co zasluzyli. jestes tego warta",
	"Przykro się na to patrzy. Też miałem problemy z pornografią, ale to już wyższy stan. Pamiętaj że możesz stać się nowym człowiekiem. Jezus to zapewnia każdemu człowiekowi. Nie zraź się, bo Jezus i jego nauki, które są w Biblii niewiele mają wspólnego z polskim katolicyzmem. Jezus to miłość, katolicyzm to władza. Dla każdego jest miejsce w Jego miłości.",
	"ja nie mam problemu z pornografia, ja mam problem z simpami i white knightami, ktorzy bronia szlauf przed odpowiedzialnoscia. kazda szlaufa ma wolny wybor, jak bog czy cokolwiek tam jest niby nam dal, my je ostrzegalismy przed konsekwencjami, bredzily ze nie bedziemy kontrolowac ich ciala a dzis placza, dzis chca nasze pianiadze na nie moje bekarty, nasze emerytury, nasze skladki zdrowotne, mimo iz ten worek na sperme nigdy nei placil, jak i nie byl ani sekundy w pracy. tak jak ukry i inne pasozyty. za trans w sporcie tez same lazily na marszach. teraz czas by zbieraly burze, za syf ktore same zasialy. chcialy byc silne i niezalezne to niech teraz maja",
	"Widzisz, to jest zniewolenie jak każde inne, ale to nie kobiety są zniewolone tylko ty...",
	"Co ty piierdolisz wieśniaku? Nie nie chciałem być śmieszny deebilu jeebany tylko mówię że mi się podoba Jinx i nie jestem peedofil bo mi się podoba dziewczyna ty Jesteś spiiierdolonym prawiczkiem więc Zamknij piizdę. Twoja matka to kuurwa jebana i robiła wszystkim lody więc Zamknij łeb śmiieciu piierdolony",
	"Jak rozumiem jesteś przeciętnym dzieckiem które nawet nie zna lore świata.",
	"@Adamuui to dupek. psy szczekaja, a karuzela kreci sie dalej hahaha",
	"Dodaj jeszcze że murzynstwo to choroba i trzeba z nia walczyć tak ja z Odrą",
	"serial dla onanistów przedział 14-37 lat, fapujących do anime. ps laski nie lecą na taki kreskówkowy shit tylko chłopców z siłki :D",
	"jestem onanistą i chłopcem z siłki, łape robie żeby mocniej bić konia i co teraz?",
	"oj malej ksiezniczki namiocik, a jadnak one wszystkie jak mowilismy lubia sie bawic w dom, dlatego zamrazaja swoje jajeczka, a na koniec odcinka odzywa sie jej kompleks tatusia. popatrz mala szm.to "little slut have no fear, daddy is here" kocham cie tatusiu, a ja ciebie moj maly woreczku, nikt nie masuje tak czule, tatusia kule. dlatego one dzis wszystkie po samotnej mamusi sa tak zagubione, bo nie wiedza kto jest ich tatusiem i w kazdym szukaja tatusia.",
	"jestes turbo lipny, krytyk filmowy sie znalazl xd , serial jest zajebisty a ty sie czepiasz nie pasuje to nie ogladaj. zjeb",
	"Joł, aha...\nSrakojebny pierdogrzmocie\nGrzebiesz w pUTINA wymiocie\nJesteś kuzwa wszędzie na wylocie\nByłeś najsłabszy w miocie\nTy psów pomiocie\nByłeś chójowy w każdym szkolnym przedmiocie\nMasz rzadkich chorób krocie\nNarodowy Fundusz Zabijania ma cię w dupy wylocie\nTy kmiocie\nW poprzednim życiu kaczyńskiego kocie\nTy najtańszy chiński młocie",
	"chłopie odstaw internet XD Syndrom oblęzonej twierdzy mocno."
]
